import '../models/station_model.dart';
import '../models/train_model.dart';
import '../models/passenger_model.dart';
import '../models/booking_model.dart';
import '../models/pnr_model.dart';
import '../models/user_model.dart';

class MockData {
  static final List<Station> stations = [
    const Station(code: 'NDLS', name: 'New Delhi', city: 'Delhi', state: 'Delhi'),
    const Station(code: 'MMCT', name: 'Mumbai Central', city: 'Mumbai', state: 'Maharashtra'),
    const Station(code: 'CSMT', name: 'Chhatrapati Shivaji Maharaj Terminus', city: 'Mumbai', state: 'Maharashtra'),
    const Station(code: 'NZM', name: 'Hazrat Nizamuddin', city: 'Delhi', state: 'Delhi'),
    const Station(code: 'HWH', name: 'Howrah Junction', city: 'Kolkata', state: 'West Bengal'),
    const Station(code: 'PNBE', name: 'Patna Junction', city: 'Patna', state: 'Bihar'),
    const Station(code: 'MAS', name: 'Chennai Central', city: 'Chennai', state: 'Tamil Nadu'),
    const Station(code: 'SBC', name: 'KSR Bengaluru', city: 'Bengaluru', state: 'Karnataka'),
    const Station(code: 'ADI', name: 'Ahmedabad Junction', city: 'Ahmedabad', state: 'Gujarat'),
    const Station(code: 'BSB', name: 'Varanasi Junction', city: 'Varanasi', state: 'Uttar Pradesh'),
    const Station(code: 'CNB', name: 'Kanpur Central', city: 'Kanpur', state: 'Uttar Pradesh'),
    const Station(code: 'LKO', name: 'Lucknow Charbagh', city: 'Lucknow', state: 'Uttar Pradesh'),
    const Station(code: 'PUNE', name: 'Pune Junction', city: 'Pune', state: 'Maharashtra'),
    const Station(code: 'JAT', name: 'Jammu Tawi', city: 'Jammu', state: 'Jammu & Kashmir'),
    const Station(code: 'ASR', name: 'Amritsar Junction', city: 'Amritsar', state: 'Punjab'),
    const Station(code: 'KOTA', name: 'Kota Junction', city: 'Kota', state: 'Rajasthan'),
    const Station(code: 'BRC', name: 'Vadodara Junction', city: 'Vadodara', state: 'Gujarat'),
    const Station(code: 'BSR', name: 'Vasai Road', city: 'Mumbai', state: 'Maharashtra'),
  ];

  static final List<Train> trains = [
    Train(
      trainNumber: '12952',
      trainName: 'Mumbai Rajdhani Express',
      trainType: 'Superfast AC Special',
      source: 'NDLS',
      sourceName: 'New Delhi',
      destination: 'MMCT',
      destinationName: 'Mumbai Central',
      departureTime: '16:55',
      arrivalTime: '08:35',
      duration: '15h 40m',
      departurePlatform: 3,
      arrivalPlatform: 1,
      runningDays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
      hasPantry: true,
      hasFoodService: true,
      punctualityPercent: 98.4,
      classes: {
        '3A': const ClassInfo(
          classCode: '3A',
          className: 'AC 3-Tier',
          availableSeats: 42,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 1855.0,
          confirmationChance: '100% Confirmed',
        ),
        '2A': const ClassInfo(
          classCode: '2A',
          className: 'AC 2-Tier',
          availableSeats: 18,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 2645.0,
          confirmationChance: '100% Confirmed',
        ),
        '1A': const ClassInfo(
          classCode: '1A',
          className: 'AC First Class',
          availableSeats: 0,
          waitlistCount: 5,
          status: 'WL',
          price: 4485.0,
          confirmationChance: '82% Probability',
        ),
      },
      stops: const [
        TrainStop(stationCode: 'NDLS', stationName: 'New Delhi', arrival: 'Source', departure: '16:55', platform: 3, distanceKm: 0),
        TrainStop(stationCode: 'KOTA', stationName: 'Kota Junction', arrival: '21:30', departure: '21:40', platform: 1, distanceKm: 465),
        TrainStop(stationCode: 'RTM', stationName: 'Ratlam Junction', arrival: '01:05', departure: '01:07', platform: 4, distanceKm: 732),
        TrainStop(stationCode: 'BRC', stationName: 'Vadodara Junction', arrival: '04:18', departure: '04:28', platform: 1, distanceKm: 992),
        TrainStop(stationCode: 'ST', stationName: 'Surat', arrival: '06:00', departure: '06:05', platform: 2, distanceKm: 1122),
        TrainStop(stationCode: 'BVI', stationName: 'Borivali', arrival: '07:58', departure: '08:00', platform: 7, distanceKm: 1356),
        TrainStop(stationCode: 'MMCT', stationName: 'Mumbai Central', arrival: '08:35', departure: 'Destination', platform: 1, distanceKm: 1386),
      ],
    ),
    Train(
      trainNumber: '22222',
      trainName: 'CSMT Vande Bharat Express',
      trainType: 'Vande Bharat • 160 km/h',
      source: 'NDLS',
      sourceName: 'New Delhi',
      destination: 'CSMT',
      destinationName: 'Mumbai CSMT',
      departureTime: '06:00',
      arrivalTime: '18:15',
      duration: '12h 15m',
      departurePlatform: 16,
      arrivalPlatform: 18,
      runningDays: ['M', 'T', 'W', 'F', 'S', 'S'],
      hasPantry: true,
      hasFoodService: true,
      punctualityPercent: 99.1,
      classes: {
        'CC': const ClassInfo(
          classCode: 'CC',
          className: 'AC Chair Car',
          availableSeats: 94,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 1665.0,
        ),
        'EC': const ClassInfo(
          classCode: 'EC',
          className: 'Exec. Chair Car',
          availableSeats: 14,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 3125.0,
        ),
      },
      stops: const [
        TrainStop(stationCode: 'NDLS', stationName: 'New Delhi', arrival: 'Source', departure: '06:00', platform: 16, distanceKm: 0),
        TrainStop(stationCode: 'KOTA', stationName: 'Kota Junction', arrival: '10:15', departure: '10:20', platform: 1, distanceKm: 465),
        TrainStop(stationCode: 'BRC', stationName: 'Vadodara Junction', arrival: '14:20', departure: '14:25', platform: 2, distanceKm: 992),
        TrainStop(stationCode: 'CSMT', stationName: 'Mumbai CSMT', arrival: '18:15', departure: 'Destination', platform: 18, distanceKm: 1384),
      ],
    ),
    Train(
      trainNumber: '12954',
      trainName: 'August Kranti Tejas Rajdhani',
      trainType: 'Tejas Smart Sleeper',
      source: 'NZM',
      sourceName: 'Hazrat Nizamuddin',
      destination: 'MMCT',
      destinationName: 'Mumbai Central',
      departureTime: '17:15',
      arrivalTime: '09:20',
      duration: '16h 05m',
      departurePlatform: 4,
      arrivalPlatform: 2,
      runningDays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
      hasPantry: true,
      hasFoodService: true,
      punctualityPercent: 93.5,
      classes: {
        '3A': const ClassInfo(
          classCode: '3A',
          className: 'AC 3-Tier',
          availableSeats: 0,
          waitlistCount: 12,
          status: 'RAC',
          price: 1780.0,
          confirmationChance: 'RAC 12 (High Chance)',
        ),
        '2A': const ClassInfo(
          classCode: '2A',
          className: 'AC 2-Tier',
          availableSeats: 6,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 2530.0,
        ),
        '1A': const ClassInfo(
          classCode: '1A',
          className: 'AC First Class',
          availableSeats: 0,
          waitlistCount: 12,
          status: 'WL',
          price: 4320.0,
          confirmationChance: '54% Probability',
        ),
      },
    ),
    Train(
      trainNumber: '12904',
      trainName: 'Golden Temple Mail',
      trainType: 'Superfast Mail',
      source: 'NDLS',
      sourceName: 'New Delhi',
      destination: 'MMCT',
      destinationName: 'Mumbai Central',
      departureTime: '07:20',
      arrivalTime: '05:20',
      duration: '22h 00m',
      departurePlatform: 5,
      arrivalPlatform: 4,
      runningDays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
      hasPantry: true,
      hasFoodService: true,
      punctualityPercent: 91.0,
      classes: {
        'SL': const ClassInfo(
          classCode: 'SL',
          className: 'Sleeper Class',
          availableSeats: 64,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 615.0,
        ),
        '3A': const ClassInfo(
          classCode: '3A',
          className: 'AC 3-Tier',
          availableSeats: 22,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 1640.0,
        ),
        '2A': const ClassInfo(
          classCode: '2A',
          className: 'AC 2-Tier',
          availableSeats: 8,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 2360.0,
        ),
        'GEN': const ClassInfo(
          classCode: 'GEN',
          className: 'Second Sitting (2S)',
          availableSeats: 110,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 360.0,
        ),
      },
    ),
    Train(
      trainNumber: '12302',
      trainName: 'Howrah Rajdhani Express',
      trainType: 'Superfast AC Special',
      source: 'NDLS',
      sourceName: 'New Delhi',
      destination: 'HWH',
      destinationName: 'Howrah Junction',
      departureTime: '16:50',
      arrivalTime: '09:55',
      duration: '17h 05m',
      departurePlatform: 9,
      arrivalPlatform: 8,
      runningDays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
      hasPantry: true,
      hasFoodService: true,
      punctualityPercent: 97.2,
      classes: {
        '3A': const ClassInfo(
          classCode: '3A',
          className: 'AC 3-Tier',
          availableSeats: 35,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 1910.0,
        ),
        '2A': const ClassInfo(
          classCode: '2A',
          className: 'AC 2-Tier',
          availableSeats: 14,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 2710.0,
        ),
      },
    ),
    Train(
      trainNumber: '12560',
      trainName: 'Shiv Ganga Express',
      trainType: 'Superfast Express',
      source: 'NDLS',
      sourceName: 'New Delhi',
      destination: 'BSB',
      destinationName: 'Varanasi Junction',
      departureTime: '20:05',
      arrivalTime: '07:10',
      duration: '11h 05m',
      departurePlatform: 12,
      arrivalPlatform: 1,
      runningDays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
      hasPantry: false,
      hasFoodService: true,
      punctualityPercent: 96.0,
      classes: {
        'SL': const ClassInfo(
          classCode: 'SL',
          className: 'Sleeper Class',
          availableSeats: 88,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 440.0,
        ),
        '3A': const ClassInfo(
          classCode: '3A',
          className: 'AC 3-Tier',
          availableSeats: 26,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 1160.0,
        ),
        '2A': const ClassInfo(
          classCode: '2A',
          className: 'AC 2-Tier',
          availableSeats: 9,
          waitlistCount: 0,
          status: 'AVAILABLE',
          price: 1650.0,
        ),
      },
    ),
  ];

  static AppUser defaultUser = AppUser(
    uid: 'user_ritesh_01',
    name: 'Ritesh Jadhav',
    email: 'ritesh.jadhav@gmail.com',
    phone: '+91 98765 43210',
    irctcUserId: 'RITESH_J2026',
    savedPassengers: [
      const SavedPassenger(
        id: 'sp_1',
        name: 'Ritesh Jadhav',
        age: 21,
        gender: 'Male',
        berthPreference: 'Side Lower (SL)',
        idType: 'Aadhaar Card',
        idNumber: 'XXXX-XXXX-8921',
      ),
      const SavedPassenger(
        id: 'sp_2',
        name: 'Pooja Jadhav',
        age: 48,
        gender: 'Female',
        berthPreference: 'Lower Berth (LB)',
        idType: 'Aadhaar Card',
        idNumber: 'XXXX-XXXX-4512',
      ),
      const SavedPassenger(
        id: 'sp_3',
        name: 'Ashok Jadhav',
        age: 54,
        gender: 'Male',
        berthPreference: 'Lower Berth (LB)',
        idType: 'PAN Card',
        idNumber: 'ABCDE1234F',
      ),
    ],
  );

  static final List<Booking> defaultBookings = [
    Booking(
      pnr: '284-9182741',
      userId: 'user_ritesh_01',
      trainNumber: '12952',
      trainName: 'Mumbai Rajdhani Express',
      trainType: 'Superfast AC Special',
      journeyDate: DateTime.now().add(const Duration(days: 1)),
      bookingDate: DateTime.now().subtract(const Duration(days: 2)),
      source: 'NDLS',
      sourceName: 'New Delhi',
      destination: 'MMCT',
      destinationName: 'Mumbai Central',
      departureTime: '16:55',
      arrivalTime: '08:35',
      departurePlatform: 3,
      arrivalPlatform: 1,
      travelClass: '3A',
      quota: 'General',
      status: 'CONFIRMED',
      isTatkal: false,
      passengers: [
        Passenger(
          id: 'p_1',
          name: 'Ritesh Jadhav',
          age: 21,
          gender: 'Male',
          berthPreference: 'Side Lower (SL)',
          currentStatus: 'CNF',
          coachNumber: 'B4',
          berthNumber: '37',
          berthType: 'Side Lower (SL)',
        ),
      ],
      fareDetails: const FareDetails(
        baseFare: 1735.0,
        tatkalCharge: 0.0,
        serviceTax: 85.0,
        convenienceFee: 35.0,
        totalFare: 1855.0,
      ),
      paymentMethod: 'Google Pay (UPI)',
      transactionId: 'RGO-TXN-9812401',
      isDownloaded: true,
    ),
    Booking(
      pnr: '642-1084920',
      userId: 'user_ritesh_01',
      trainNumber: '22222',
      trainName: 'CSMT Vande Bharat Express',
      trainType: 'Vande Bharat • 160 km/h',
      journeyDate: DateTime.now().subtract(const Duration(days: 7)),
      bookingDate: DateTime.now().subtract(const Duration(days: 14)),
      source: 'NDLS',
      sourceName: 'New Delhi',
      destination: 'CSMT',
      destinationName: 'Mumbai CSMT',
      departureTime: '06:00',
      arrivalTime: '18:15',
      departurePlatform: 16,
      arrivalPlatform: 18,
      travelClass: 'CC',
      quota: 'General',
      status: 'CONFIRMED',
      isTatkal: false,
      passengers: [
        Passenger(
          id: 'p_2',
          name: 'Ritesh Jadhav',
          age: 21,
          gender: 'Male',
          currentStatus: 'CNF',
          coachNumber: 'C3',
          berthNumber: '42',
          berthType: 'Window (WS)',
        ),
      ],
      fareDetails: const FareDetails(
        baseFare: 1550.0,
        tatkalCharge: 0.0,
        serviceTax: 80.0,
        convenienceFee: 35.0,
        totalFare: 1665.0,
      ),
      paymentMethod: 'PhonePe (UPI)',
      transactionId: 'RGO-TXN-7731204',
      isDownloaded: false,
    ),
  ];

  static final Map<String, PNRStatus> pnrDatabase = {
    '284-9182741': PNRStatus(
      pnr: '284-9182741',
      trainNumber: '12952',
      trainName: 'Mumbai Rajdhani Express',
      source: 'NDLS',
      destination: 'MMCT',
      journeyDate: DateTime.now().add(const Duration(days: 1)),
      travelClass: '3A',
      quota: 'General',
      chartPrepared: true,
      currentStation: 'Approaching Kota Junction (Platform 1)',
      delayMinutes: 0,
      expectedPlatform: 3,
      passengers: const [
        PassengerPNRStatus(
          serialNo: 1,
          bookingStatus: 'CNF',
          currentStatus: 'CNF',
          coach: 'B4',
          berth: '37',
          berthType: 'Side Lower (SL)',
        ),
      ],
    ),
    '642-1084920': PNRStatus(
      pnr: '642-1084920',
      trainNumber: '22222',
      trainName: 'CSMT Vande Bharat Express',
      source: 'NDLS',
      destination: 'CSMT',
      journeyDate: DateTime.now().subtract(const Duration(days: 7)),
      travelClass: 'CC',
      quota: 'General',
      chartPrepared: true,
      currentStation: 'Journey Completed at Mumbai CSMT',
      delayMinutes: 0,
      expectedPlatform: 18,
      passengers: const [
        PassengerPNRStatus(
          serialNo: 1,
          bookingStatus: 'CNF',
          currentStatus: 'CNF',
          coach: 'C3',
          berth: '42',
          berthType: 'Window',
        ),
      ],
    ),
    '812-4091823': PNRStatus(
      pnr: '812-4091823',
      trainNumber: '12954',
      trainName: 'August Kranti Tejas Rajdhani',
      source: 'NZM',
      destination: 'MMCT',
      journeyDate: DateTime.now().add(const Duration(days: 3)),
      travelClass: '3A',
      quota: 'General',
      chartPrepared: false,
      currentStation: 'Train in yard for maintenance',
      delayMinutes: 10,
      expectedPlatform: 4,
      passengers: const [
        PassengerPNRStatus(
          serialNo: 1,
          bookingStatus: 'WL 14',
          currentStatus: 'RAC 4',
          coach: 'Chart Not Prepared',
          berth: 'Will allocate at charting',
        ),
      ],
    ),
  };

  static List<Booking> get sampleBookings => defaultBookings;
  static List<Booking> get bookings => defaultBookings;

  static PNRStatus? getPNRStatus(String pnr) {
    return pnrDatabase[pnr];
  }

  static List<Train> searchTrains({String? from, String? to, DateTime? date}) {
    return trains;
  }
}

